// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXNLjXyFupLFc_l4le_3vKe1yd2dkX-4',
    appId: '1:540308402084:web:eaf21b4e4abcf1d2719b31',
    messagingSenderId: '540308402084',
    projectId: 'assistant-1-491ec',
    authDomain: 'assistant-1-491ec.firebaseapp.com',
    storageBucket: 'assistant-1-491ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjheRqAxUZkfG1GzdgkSSuW1EgVGe-x0Q',
    appId: '1:540308402084:android:2b4b49d8960d19f4719b31',
    messagingSenderId: '540308402084',
    projectId: 'assistant-1-491ec',
    storageBucket: 'assistant-1-491ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXye8t6mgvJ3rFNqdFC6mddeJ18H0gu5U',
    appId: '1:540308402084:ios:cf13584fc8c43f6f719b31',
    messagingSenderId: '540308402084',
    projectId: 'assistant-1-491ec',
    storageBucket: 'assistant-1-491ec.firebasestorage.app',
    iosClientId: '540308402084-kkrcqlcoe1fartr07mccs6m94ichru14.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXye8t6mgvJ3rFNqdFC6mddeJ18H0gu5U',
    appId: '1:540308402084:ios:cf13584fc8c43f6f719b31',
    messagingSenderId: '540308402084',
    projectId: 'assistant-1-491ec',
    storageBucket: 'assistant-1-491ec.firebasestorage.app',
    iosClientId: '540308402084-kkrcqlcoe1fartr07mccs6m94ichru14.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUXNLjXyFupLFc_l4le_3vKe1yd2dkX-4',
    appId: '1:540308402084:web:92ee884ffab03d00719b31',
    messagingSenderId: '540308402084',
    projectId: 'assistant-1-491ec',
    authDomain: 'assistant-1-491ec.firebaseapp.com',
    storageBucket: 'assistant-1-491ec.firebasestorage.app',
  );
}
